// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0bb1Pn4_liyZC-3DUvhiW6GDI2khUN4',
    appId: '1:293815928522:web:e235ac8652244f39599633',
    messagingSenderId: '293815928522',
    projectId: 'citoact',
    authDomain: 'citoact.firebaseapp.com',
    storageBucket: 'citoact.appspot.com',
    measurementId: 'G-HBG365LBG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdh1Tq0LLGHLjqb2nTznLhFSqmzOPSt2w',
    appId: '1:293815928522:android:3992337dc413e82b599633',
    messagingSenderId: '293815928522',
    projectId: 'citoact',
    storageBucket: 'citoact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXH7QrwQBoHlE4ROys9xHlYZzuJTycCiQ',
    appId: '1:293815928522:ios:569cd94ba63274c9599633',
    messagingSenderId: '293815928522',
    projectId: 'citoact',
    storageBucket: 'citoact.appspot.com',
    iosBundleId: 'com.example.citoActMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXH7QrwQBoHlE4ROys9xHlYZzuJTycCiQ',
    appId: '1:293815928522:ios:569cd94ba63274c9599633',
    messagingSenderId: '293815928522',
    projectId: 'citoact',
    storageBucket: 'citoact.appspot.com',
    iosBundleId: 'com.example.citoActMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY0bb1Pn4_liyZC-3DUvhiW6GDI2khUN4',
    appId: '1:293815928522:web:a7d50d75d0a86c64599633',
    messagingSenderId: '293815928522',
    projectId: 'citoact',
    authDomain: 'citoact.firebaseapp.com',
    storageBucket: 'citoact.appspot.com',
    measurementId: 'G-M6CRYBGJF5',
  );
}
